# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kT4Ysz2J7zV3k3Bqjy9R00rJwJ_3X0R6
"""

# AI Lab - Week 2
# 8 Puzzle using Iterative Deepening Search (IDS)

initial = [
    [1, 2, 3],
    [4, 5, 6],
    [0, 7, 8]
]

goal = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 0]
]


# Find blank position
def find_blank(state):
    for i in range(3):
        for j in range(3):
            if state[i][j] == 0:
                return i, j


# Generate next states
def moves(state):
    r, c = find_blank(state)
    result = []

    directions = [
        (-1, 0),
        (1, 0),
        (0, -1),
        (0, 1)
    ]

    for dr, dc in directions:
        nr = r + dr
        nc = c + dc

        if 0 <= nr < 3 and 0 <= nc < 3:

            new = [row[:] for row in state]

            new[r][c], new[nr][nc] = \
                new[nr][nc], new[r][c]

            result.append(new)

    return result


# Depth Limited Search
def DLS(state, depth, path):

    if state == goal:
        return path

    if depth == 0:
        return None

    for new_state in moves(state):

        if new_state not in path:

            result = DLS(
                new_state,
                depth - 1,
                path + [new_state]
            )

            if result:
                return result

    return None


# IDS
def IDS():

    for depth in range(20):

        print("Depth:", depth)

        result = DLS(initial, depth, [initial])

        if result:
            return result

    return None


# Print state
def print_state(state):
    for row in state:
        print(row)
    print()


# Main
print("Initial State:")
print_state(initial)

print("Goal State:")
print_state(goal)

solution = IDS()

if solution:

    print("Solution Found!")
    print("Moves:", len(solution) - 1)
    print()

    for i, state in enumerate(solution):
        print("Step", i)
        print_state(state)

else:
    print("No solution found.")

Output
Initial State:
[1, 2, 3]
[4, 5, 6]
[0, 7, 8]

Goal State:
[1, 2, 3]
[4, 5, 6]
[7, 8, 0]

Depth: 0
Depth: 1
Depth: 2

Solution Found!
Moves: 2

Step 0
[1, 2, 3]
[4, 5, 6]
[0, 7, 8]

Step 1
[1, 2, 3]
[4, 5, 6]
[7, 0, 8]

Step 2
[1, 2, 3]
[4, 5, 6]
[7, 8, 0]


This is much more suitable for an AI Lab record, because the IDS logic is easy to explain: DLS searches up to a depth, then IDS increases the depth one by one.